services:
  db:
    image: postgres:15-alpine
    container_name: mefeed_db_simple
    environment:
      POSTGRES_DB: mefeed
      POSTGRES_USER: mefeed_user
      POSTGRES_PASSWORD: mefeed_pass_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mefeed_redis_simple
    command: redis-server --requirepass kN7R4xWvE2sDcF9TpYqh6LmGzJ8Kb3Ua5Hn1VtwMXQ0r
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "kN7R4xWvE2sDcF9TpYqh6LmGzJ8Kb3Ua5Hn1VtwMXQ0r", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
